name: Code Style CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  codestyle:
    name: Check code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Setting the token for installing private package
        run: sed -i 's/NPM_AUTH_TOKEN=.*/NPM_AUTH_TOKEN=${{ secrets.NPM_AUTH_TOKEN }}/' .env

      - name: Install the github token
        run: make token

      - name: Install the Node.js dependencies
        run: make install

      - name: Check if the code style of the source-codes is consistently applied
        run: make lint